version: '3'
services:
  php-fpm:
    build:
      context: docker/php-fpm
    volumes:
      - ./src/:/var/www
    environment:
      XDEBUG_CONFIG: "remote_host=host.docker.internal remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
    depends_on:
      - mariadb
    networks:
      - internal
  mariadb:
    build:
      context: docker/mariadb
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    networks:
      - internal
  nginx:
    build:
      context: docker/nginx
    volumes:
      - ./src/:/var/www
    ports:
      - 80:80
    depends_on:
      - php-fpm
    networks:
      - internal
networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.220.0/28